{% set name = "reef3d" %}
{% set version = "23.08" %}
#  # sha256 is the preferred checksum -- you can get it for a file with:
#  #  `openssl sha256 <file name>`.
#  # You may need the openssl package, available on conda-forge:
#  #  `conda install openssl -c conda-forge``
#{% set sha256 = "61d9216cf81d246944720cfce96255878a3f85dec13b9351f1fa0fd6768220a6" %}

{% set mpi = mpi or 'openmpi' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/REEF3D/REEF3D/archive/refs/tags/{{ version }}.tar.gz
#  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - make
    - {{ compiler('fortran') }}
    - {{ compiler('cxx') }}
    - hypre
    - {{ mpi }}
  host:
    - hypre
    - {{ mpi }}
  run:
    - hypre
    - {{ mpi }}

test:
  commands:
    - test -f $PREFIX/bin/reef3d  # [linux, osx]

about:
  home: https://reef3d.wordpress.com/
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: "REEF3D : Open-Source Hydrodynamics"
  description: |
    REEF3D is an open-source hydrodynamics framework.  The software is efficiently parallelized, 
    designed to run on a large number of processors. High-order spatial and temporal discretization 
    schemes result in accurate and stable numerical behavior. The modular programming approach 
    allows the framework to incorporate a range of different flow solvers which together represent
    all relevant length scales. With a focus on coastal, marine and hydraulic engineering flows, 
    tailor-made multiphysics solvers are available for a range of relevant problems 
    (e.g. sediment transport or floating body dynamics).

extra:
  recipe-maintainers:
    - mattkram
